import { useState, useEffect } from 'react';
import { Bell, X, Check, Loader2 } from 'lucide-react';
import { Button } from './ui/Button.js';
import { apiGet, apiPost } from '../lib/api.js';
import type { PushSubscriptionCreateRequest, PushSubscriptionResponse } from '@ddt/shared';

// Base64 helper for VAPID key conversion
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export async function requestAndRegisterPush(): Promise<boolean> {
  if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
    console.warn('Push notifications are not supported in this browser.');
    return false;
  }

  try {
    // 1. Fetch public VAPID key
    const configRes = await apiGet<{ vapidPublicKey: string }>('/push-subscriptions/config');
    if (!configRes.success) {
      throw new Error(configRes.message);
    }
    const vapidPublicKey = configRes.data.vapidPublicKey;

    // 2. Request browser permission
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return false;
    }

    // 3. Register push subscription
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(vapidPublicKey) as unknown as BufferSource,
    });

    // 4. Save to backend
    const subJson = subscription.toJSON();
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      throw new Error('Invalid push subscription structure generated by browser');
    }

    const saveRes = await apiPost<PushSubscriptionCreateRequest, { subscription: PushSubscriptionResponse }>('/push-subscriptions', {
      endpoint: subJson.endpoint,
      keys: {
        p256dh: subJson.keys.p256dh,
        auth: subJson.keys.auth,
      },
    });

    return saveRes.success;
  } catch (err) {
    console.error('Error subscribing to push notifications:', err);
    return false;
  }
}

interface NotificationPermissionBannerProps {
  settingsEnabled: boolean;
  onPermissionGranted: () => void;
}

export function NotificationPermissionBanner({ settingsEnabled, onPermissionGranted }: NotificationPermissionBannerProps) {
  const [permissionState, setPermissionState] = useState<NotificationPermission>('default');
  const [isPrompting, setIsPrompting] = useState(false);
  const [showBanner, setShowBanner] = useState(true);

  useEffect(() => {
    if ('Notification' in window) {
      setPermissionState(Notification.permission);
    }
  }, []);

  const handleGrant = async () => {
    setIsPrompting(true);
    const success = await requestAndRegisterPush();
    setIsPrompting(false);
    if ('Notification' in window) {
      setPermissionState(Notification.permission);
    }
    if (success) {
      onPermissionGranted();
    }
  };

  // Only show banner if setting is enabled but browser permission is not yet granted
  if (!settingsEnabled || permissionState === 'granted' || !showBanner || !('Notification' in window)) {
    return null;
  }

  return (
    <div className="bg-primary/10 border border-primary/20 p-4 rounded-xl flex items-center justify-between gap-3 text-foreground shadow-sm">
      <div className="flex items-center gap-3 min-w-0">
        <div className="p-2 bg-primary/20 text-primary rounded-lg shrink-0">
          <Bell className="w-5 h-5" />
        </div>
        <div className="min-w-0">
          <h5 className="text-sm font-semibold">Enable Browser Notifications</h5>
          <p className="text-xs text-muted-foreground truncate max-w-lg md:max-w-2xl">
            {permissionState === 'denied'
              ? 'Notification permission is blocked. Please reset site permissions in your browser settings to receive alerts.'
              : 'Grant notification permission to get alerted before your scheduled daily tasks begin.'}
          </p>
        </div>
      </div>
      <div className="flex items-center gap-2 shrink-0">
        {permissionState !== 'denied' && (
          <Button variant="primary" size="sm" onClick={handleGrant} disabled={isPrompting}>
            {isPrompting ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <>
                <Check className="w-4 h-4 mr-1" />
                Enable
              </>
            )}
          </Button>
        )}
        <button
          type="button"
          onClick={() => setShowBanner(false)}
          className="p-1 rounded text-muted-foreground hover:bg-muted"
          aria-label="Dismiss banner"
        >
          <X className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}
